export const SET_NAV_STATE = 'SET_NAV_STATE';
export const SUBMITTED_EMAIL = 'SUBMITTED_EMAIL';
export const REQUEST_PROJECTS = 'REQUEST_PROJECTS';
export const REQUEST_PROJECTS_SUCCESS = 'REQUEST_PROJECTS_SUCCESS';
export const REQUEST_PROJECTS_FAILURE = 'REQUEST_PROJECTS_FAILURE';
export const REQUEST_ANIMATION_LIBRARIES = 'REQUEST_ANIMATION_LIBRARIES';
export const REQUEST_ANIMATION_LIBRARIES_SUCCESS = 'REQUEST_ANIMATION_LIBRARIES_SUCCESS';
export const REQUEST_ANIMATION_LIBRARIES_FAILURE = 'REQUEST_ANIMATION_LIBRARIES_FAILURE';
